spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:
    username: user
    password: password
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type : trace
